### ISSUE TITLE
OpenNLP Models Singleton Initialization

### ISSUE THREAD

**Issue by rafaharo** [ChalithaUdara/OpenNLP-Manifold-Connector#1]
OpenNLP models used to be very heavy, but they are Thread Safe (http://opennlp.apache.org/documentation/apidocs/opennlp-tools/opennlp/tools/tokenize/TokenizerME.html). You should avoid loading them for each call to the addOrReplaceDocumentWithException. That could be extremely slow. You can just initialize the models statically and provide a factory of Finders that are initialized using those pre-loaded models (because the finders, tokenizers, sentence splitter, etc... ARE NOT THREAD SAFE, but the models are). I can provide a pull request

**Comment by ChalithaUdara** [comment]
Hi Rafa,

Totally agree with you. It would be great if you can provide a pull request.

Thank you
